[workspace]
resolver = "3"
members = [
  "examples",
  "membrane-core",
  "membrane-macros",
  "membrane-openai",
  "membrane-tools",
]

[workspace.lints.clippy]
unwrap_used = "deny"

[workspace.dependencies]
reqwest = { version = "0.12", features = ["json"] }
schemars = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
tracing = "0.1"
