[package]
name = "membrane-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3"
membrane-core = { path = "../membrane-core" }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[lints]
workspace = true
