[package]
name = "membrane-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
membrane-core = { path = "../membrane-core" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
tracing = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
