[package]
name = "membrane-core"
version = "0.1.0"
edition = "2024"

[dependencies]
membrane-macros = { path = "../membrane-macros" }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt"] }
